# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'),
            preserve_default=False,
        ),
    ]
