# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20160219_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='html_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
